apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 80           # Port exposed inside the cluster
      targetPort: 3000   # Port your application listens on inside the pods
  type: ClusterIP
